### PR TITLE
chore: Upgrade to Nx 17.1.3

### PR DESCRIPTION
**Pull request by simondotm**
It is time to move on from 16.x

### CODE REVIEW

**Comment by jaytavares** [comment]
@simondotm Is this a bad time to mention that Nx@latest is at v18? 😂

**Comment by simondotm** [comment]
@jaytavares 
haha, you know what, I have previous trauma from skipping Nx versions during the updates for this plugin. They change stuff so fast, sometimes it is easier to just update incrementally.
I already found that 17.3.2 has some changes that break some of my e2e tests in some way.

Plus, there's the added complication that there are still users out there using older Nx versions in their projects and I like to try and keep the plugin as widely compatible as I can. 👍

**Comment by jaytavares** [comment]
I feel that pain. PTSD from every time I've run `nx migrate` - though in Nrwl's defense, it's mainly thanks to npm dependency hell. 

Perhaps semver could protect against the breaking change issues? While at it, you could even update the plugin version to mirror the nx major version.

**Comment by simondotm** [comment]
> you could even update the plugin version to mirror the nx major version.

This is an idea that I have considered before. What stopped me going down this path is that:
1. I basically wrote this plugin to help me with my own firebase project developments
2. I am one of the folks with projects on older Nx versions. 

I should really get on board with upgrading them as I go, and its probably easier to do now, since Nx decoupled angular version from the Nx version (I use angular a lot in my personal projects).

That said, the idea of continuously supporting this plugin with every new Nx release doesnt thrill me. I need to get some work done, not just spend my days updating dependencies all the time! 😂

**Comment by simondotm** [comment]
Closing in favour of #205

**Pull request closed without merging**
