### PR TITLE
Upgrade to NX Version 13

### PR DESCRIPTION
**Pull request by BraunreutherA**
As this project doesn't work anymore with NX version 13, this PR changed the V12 `createProjectGraph()` function to `await createProjectGraphAsync('4.0')` which is backward compatible through the version number. This only fixes the existing problem with the newer NX version - still the plugin should be refactored to use the new projectGraph Version.

### CODE REVIEW

**Comment by johngrimsey** [comment]
@simondotm Keen for this one 👍

**Comment by paxforce** [comment]
Hi @simondotm, is this PR going to be merged any time soon?

**Comment by enchorb** [comment]
@simondotm Would be great to get this merged so we can stop using the patch in prod

**Comment by ProductOfAmerica** [comment]
@simondotm Please man, I don't even know this repo's code, and finished the code review in exactly 15 minutes and 32 seconds. I'm sure you can spare 15 minutes of your time to approve this.

**Comment by johngrimsey** [comment]
Also, cheers @BraunreutherA 👏

**Comment by ziolmar** [comment]
+1

**Comment by sk91** [comment]
+1

**Comment by wojtiku** [comment]
+1 for this, please :)

**Comment by mati0090** [comment]
obraz

**Comment by victorouse** [comment]
+1

**Comment by josh-israel** [comment]
Any news about @simondotm ?

**Comment by Hadjimina** [comment]
This would help me out a lot! Thanks for your work @simondotm.

**Comment by simondotm** [comment]
Hi all, apologies for not being on top of this. Please see my post here: https://github.com/simondotm/nx-firebase/issues/46

Thankyou all for your contributions and suggestions. I had no idea this repo was of such interest and I will do what I can to help it be managed by the community.

To expediate things I will bless this PR without any review since everyone above seems to like it, plus I've also invited [BraunreutherA](https://github.com/BraunreutherA) to be a collaborator to start opening this project up to the community.

Cheers
Simon

**Comment by romshiri** [comment]
@simondotm Thanks, which version include the fix? When I try to download the latest version (0.3.3) I still get the error this PR suppose to fix.

**Comment by simondotm** [comment]
Hi folks I quickly tried to get a new release out last Friday but the GitHub action failed for some reason.
 I'm not at my computer now for a few days so the soonest I can look into it will be this weekend.

**Comment by adamstret** [comment]
Ok It's been more than 3 months now. Anybody considers forking this repo and implementing a fix? I'm not that skilled, but I'm eager to learn and collaborate. Anybody up for it?

**Comment by johngrimsey** [comment]
This has been a very helpful lib for me and I'm grateful to @simondotm for his efforts.

At present I'm only running one set of Firebase Functions, and all my individual apps share the same Firebase project.

I've decided to remove this as a dependency from my project and have opted instead for a standard Nx Node app, things are much simpler now for me.

**Comment by adamstret** [comment]
Hey @johngrimsey is there a tutorial that you followed when implementing it? If so, could you pls post a link?

**Pull request merged**
