### PR TITLE
Add sourcemaps & emulator debugging support

### PR DESCRIPTION
**Pull request by ciriousjoker**
- Generate sourcemaps so the debugger can find the .ts files
- Enable --inspect-functions so

### Caveat

1. Debugger disconnects when saving files (because everything recompiles & emulators seem to restart).
2. I didn't test this yet, I just added the flags where it made sense (adding them works in a real project though)
3. I wrote no documentation for this for now

### CODE REVIEW

**Comment by simondotm** [comment]
This PR looks good, thanks for the contribution.

I would like to propose that further additions are needed before we could release this feature:
* e2e tests should verify that `build` output does indeed generate `*.js.map` files in `dist`
* Since this feature changes the `project.json` schema, we should update the plugin migration tool to add these changes to existing plugin users workspace firebase projects.
* Discuss if map files should be deployed or ignored
  * If they are deployed, we'd need to document how plugin users can use them such as described [here](https://stackoverflow.com/questions/63282527/how-to-show-typescript-source-in-firebase-cloud-function-callable-stacktraces/63866829#63866829) 
  * If not, we'd need to add ignore rules to function configs for `*.map` files
* As you already mentioned, we should also document these new enhancements. 

I'm going to hold this PR here for now, while I plan out what is needed in the next release, and if this feature can be included with all of the above.

**Comment by ciriousjoker** [comment]
I have no clue how to add the remaining stuff like e2e tests and schema migrations

**Comment by dzivoing** [comment]
Has this been merged ? I am trying to debug functions with no success

**Comment by simondotm** [comment]
I've moved tests around so I'll resolve the conflict/merge from master.

**Comment by simondotm** [comment]
@ciriousjoker I would like to merge your PR, but because it is merging commits directly to main I cannot accept it.

If you could please sync your fork with the latest from my repo, then re-create your changes on a separate PR branch on your fork and re-submit the PR I'll merge it, and you will keep the contribution credit for this change.

Thanks

**Comment by ciriousjoker** [comment]
@simondotm there you go

**Pull request closed without merging**
